# when pipeline is executed, a folder named artifacts will be created

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/vijay-kshitij/MLFlow/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  # status file will return true/false depending on whether the data is in
  # correct format to enter into the training pipeline.
  STATUS_FILE: artifacts/data_validation/status.txt  
